// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const addTag = `-- name: AddTag :exec
INSERT INTO contact_tags(jid, tag, updated_at)
VALUES(?, ?, ?)
ON CONFLICT(jid, tag) DO UPDATE SET updated_at=excluded.updated_at
`

type AddTagParams struct {
	Jid       string
	Tag       string
	UpdatedAt int64
}

func (q *Queries) AddTag(ctx context.Context, arg AddTagParams) error {
	_, err := q.db.ExecContext(ctx, addTag, arg.Jid, arg.Tag, arg.UpdatedAt)
	return err
}

const clearAllSystemNames = `-- name: ClearAllSystemNames :execrows
UPDATE contacts SET system_name = NULL, updated_at = ? WHERE system_name IS NOT NULL AND system_name != ''
`

func (q *Queries) ClearAllSystemNames(ctx context.Context, updatedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearAllSystemNames, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countChatMessages = `-- name: CountChatMessages :one
SELECT COUNT(1) FROM messages WHERE chat_jid = ?
`

func (q *Queries) CountChatMessages(ctx context.Context, chatJid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChatMessages, chatJid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChats = `-- name: CountChats :one
SELECT COUNT(1) FROM chats
`

func (q *Queries) CountChats(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT COUNT(1) FROM groups WHERE left_at IS NULL
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLeftGroups = `-- name: CountLeftGroups :one
SELECT COUNT(1) FROM groups WHERE left_at IS NOT NULL
`

func (q *Queries) CountLeftGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLeftGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(1) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingMediaDownloads = `-- name: CountPendingMediaDownloads :one
SELECT COUNT(*)
FROM messages m
WHERE COALESCE(m.media_type,'') != ''
  AND COALESCE(m.direct_path,'') != ''
  AND m.media_key IS NOT NULL AND length(m.media_key) > 0
  AND COALESCE(m.local_path,'') = ''
  AND m.deleted_at IS NULL
  AND m.media_unavailable_at IS NULL
  AND (?1 = '' OR m.chat_jid = ?1)
`

func (q *Queries) CountPendingMediaDownloads(ctx context.Context, chatJid interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingMediaDownloads, chatJid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSystemNames = `-- name: CountSystemNames :one
SELECT COUNT(1) FROM contacts WHERE system_name IS NOT NULL AND system_name != ''
`

func (q *Queries) CountSystemNames(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSystemNames)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE jid = ?
`

func (q *Queries) DeleteChat(ctx context.Context, jid string) error {
	_, err := q.db.ExecContext(ctx, deleteChat, jid)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE jid = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, jid string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, jid)
	return err
}

const deleteGroupParticipants = `-- name: DeleteGroupParticipants :exec
DELETE FROM group_participants WHERE group_jid = ?
`

func (q *Queries) DeleteGroupParticipants(ctx context.Context, groupJid string) error {
	_, err := q.db.ExecContext(ctx, deleteGroupParticipants, groupJid)
	return err
}

const deleteLeftGroups = `-- name: DeleteLeftGroups :execrows
DELETE FROM groups WHERE left_at IS NOT NULL
`

func (q *Queries) DeleteLeftGroups(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLeftGroups)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLeftGroupsOlderThan = `-- name: DeleteLeftGroupsOlderThan :execrows
DELETE FROM groups WHERE left_at IS NOT NULL AND left_at < ?
`

func (q *Queries) DeleteLeftGroupsOlderThan(ctx context.Context, leftAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLeftGroupsOlderThan, leftAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMessageLocation = `-- name: DeleteMessageLocation :exec
DELETE FROM message_locations WHERE chat_jid = ? AND msg_id = ?
`

type DeleteMessageLocationParams struct {
	ChatJid string
	MsgID   string
}

func (q *Queries) DeleteMessageLocation(ctx context.Context, arg DeleteMessageLocationParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageLocation, arg.ChatJid, arg.MsgID)
	return err
}

const deleteMessageLocationsForChat = `-- name: DeleteMessageLocationsForChat :exec
DELETE FROM message_locations WHERE chat_jid = ?
`

func (q *Queries) DeleteMessageLocationsForChat(ctx context.Context, chatJid string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageLocationsForChat, chatJid)
	return err
}

const deletePoll = `-- name: DeletePoll :exec
DELETE FROM polls WHERE chat_jid = ? AND msg_id = ?
`

type DeletePollParams struct {
	ChatJid string
	MsgID   string
}

func (q *Queries) DeletePoll(ctx context.Context, arg DeletePollParams) error {
	_, err := q.db.ExecContext(ctx, deletePoll, arg.ChatJid, arg.MsgID)
	return err
}

const deletePollVote = `-- name: DeletePollVote :exec
DELETE FROM poll_votes
WHERE chat_jid = ? AND poll_msg_id = ? AND voter_jid = ? AND ts <= ?
`

type DeletePollVoteParams struct {
	ChatJid   string
	PollMsgID string
	VoterJid  string
	Ts        int64
}

func (q *Queries) DeletePollVote(ctx context.Context, arg DeletePollVoteParams) error {
	_, err := q.db.ExecContext(ctx, deletePollVote,
		arg.ChatJid,
		arg.PollMsgID,
		arg.VoterJid,
		arg.Ts,
	)
	return err
}

const deletePollVotesForChat = `-- name: DeletePollVotesForChat :exec
DELETE FROM poll_votes WHERE chat_jid = ?
`

func (q *Queries) DeletePollVotesForChat(ctx context.Context, chatJid string) error {
	_, err := q.db.ExecContext(ctx, deletePollVotesForChat, chatJid)
	return err
}

const deletePollVotesForPoll = `-- name: DeletePollVotesForPoll :exec
DELETE FROM poll_votes WHERE chat_jid = ? AND poll_msg_id = ?
`

type DeletePollVotesForPollParams struct {
	ChatJid   string
	PollMsgID string
}

func (q *Queries) DeletePollVotesForPoll(ctx context.Context, arg DeletePollVotesForPollParams) error {
	_, err := q.db.ExecContext(ctx, deletePollVotesForPoll, arg.ChatJid, arg.PollMsgID)
	return err
}

const deletePollsForChat = `-- name: DeletePollsForChat :exec
DELETE FROM polls WHERE chat_jid = ?
`

func (q *Queries) DeletePollsForChat(ctx context.Context, chatJid string) error {
	_, err := q.db.ExecContext(ctx, deletePollsForChat, chatJid)
	return err
}

const deleteStarredForChat = `-- name: DeleteStarredForChat :exec
DELETE FROM starred WHERE chat_jid = ?
`

func (q *Queries) DeleteStarredForChat(ctx context.Context, chatJid string) error {
	_, err := q.db.ExecContext(ctx, deleteStarredForChat, chatJid)
	return err
}

const findPollByMsgID = `-- name: FindPollByMsgID :one
SELECT p.chat_jid, p.msg_id, COALESCE(p.sender_jid,''), p.question, p.options_json, p.selectable_count, p.created_ts
FROM polls p
LEFT JOIN messages m ON m.chat_jid = p.chat_jid AND m.msg_id = p.msg_id
WHERE p.msg_id = ?
  AND (m.msg_id IS NULL OR m.deleted_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM message_payload_purges x WHERE x.chat_jid = p.chat_jid AND x.msg_id = p.msg_id)
ORDER BY p.created_ts DESC
LIMIT 1
`

type FindPollByMsgIDRow struct {
	ChatJid         string
	MsgID           string
	SenderJid       string
	Question        string
	OptionsJson     string
	SelectableCount int64
	CreatedTs       int64
}

func (q *Queries) FindPollByMsgID(ctx context.Context, msgID string) (FindPollByMsgIDRow, error) {
	row := q.db.QueryRowContext(ctx, findPollByMsgID, msgID)
	var i FindPollByMsgIDRow
	err := row.Scan(
		&i.ChatJid,
		&i.MsgID,
		&i.SenderJid,
		&i.Question,
		&i.OptionsJson,
		&i.SelectableCount,
		&i.CreatedTs,
	)
	return i, err
}

const getChat = `-- name: GetChat :one
SELECT jid, kind, COALESCE(name,''), COALESCE(last_message_ts,0), COALESCE(archived,0), COALESCE(pinned,0), COALESCE(muted_until,0), COALESCE(unread,0), COALESCE(unread_count,0)
FROM chats
WHERE jid = ?
`

type GetChatRow struct {
	Jid           string
	Kind          string
	Name          string
	LastMessageTs int64
	Archived      int64
	Pinned        int64
	MutedUntil    int64
	Unread        int64
	UnreadCount   int64
}

func (q *Queries) GetChat(ctx context.Context, jid string) (GetChatRow, error) {
	row := q.db.QueryRowContext(ctx, getChat, jid)
	var i GetChatRow
	err := row.Scan(
		&i.Jid,
		&i.Kind,
		&i.Name,
		&i.LastMessageTs,
		&i.Archived,
		&i.Pinned,
		&i.MutedUntil,
		&i.Unread,
		&i.UnreadCount,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT c.jid,
       COALESCE(c.phone,'') AS phone,
       COALESCE(NULLIF(a.alias,''), '') AS alias,
       COALESCE(NULLIF(c.system_name,''), '') AS system_name,
       COALESCE(NULLIF(a.alias,''), NULLIF(c.system_name,''), NULLIF(c.full_name,''), NULLIF(c.push_name,''), NULLIF(c.business_name,''), NULLIF(c.first_name,''), '') AS name,
       c.updated_at
FROM contacts c
LEFT JOIN contact_aliases a ON a.jid = c.jid
WHERE c.jid = ?
`

type GetContactRow struct {
	Jid        string
	Phone      string
	Alias      interface{}
	SystemName interface{}
	Name       interface{}
	UpdatedAt  int64
}

func (q *Queries) GetContact(ctx context.Context, jid string) (GetContactRow, error) {
	row := q.db.QueryRowContext(ctx, getContact, jid)
	var i GetContactRow
	err := row.Scan(
		&i.Jid,
		&i.Phone,
		&i.Alias,
		&i.SystemName,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMessageInfo = `-- name: GetLatestMessageInfo :one
SELECT m.chat_jid, m.msg_id, m.ts, m.from_me, COALESCE(m.sender_jid,''), COALESCE(m.sender_name,'')
FROM messages m
WHERE m.chat_jid = ?
ORDER BY m.ts DESC, m.rowid DESC
LIMIT 1
`

type GetLatestMessageInfoRow struct {
	ChatJid    string
	MsgID      string
	Ts         int64
	FromMe     int64
	SenderJid  string
	SenderName string
}

func (q *Queries) GetLatestMessageInfo(ctx context.Context, chatJid string) (GetLatestMessageInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestMessageInfo, chatJid)
	var i GetLatestMessageInfoRow
	err := row.Scan(
		&i.ChatJid,
		&i.MsgID,
		&i.Ts,
		&i.FromMe,
		&i.SenderJid,
		&i.SenderName,
	)
	return i, err
}

const getMediaDownloadInfo = `-- name: GetMediaDownloadInfo :one
SELECT m.chat_jid,
       COALESCE(c.name,''),
       m.msg_id,
       COALESCE(m.media_type,''),
       COALESCE(m.filename,''),
       COALESCE(m.mime_type,''),
       COALESCE(m.direct_path,''),
       m.media_key,
       m.file_sha256,
       m.file_enc_sha256,
       COALESCE(m.file_length,0),
       COALESCE(m.local_path,''),
       COALESCE(m.downloaded_at,0)
FROM messages m
LEFT JOIN chats c ON c.jid = m.chat_jid
WHERE m.chat_jid = ? AND m.msg_id = ?
`

type GetMediaDownloadInfoParams struct {
	ChatJid string
	MsgID   string
}

type GetMediaDownloadInfoRow struct {
	ChatJid       string
	Name          string
	MsgID         string
	MediaType     string
	Filename      string
	MimeType      string
	DirectPath    string
	MediaKey      []byte
	FileSha256    []byte
	FileEncSha256 []byte
	FileLength    int64
	LocalPath     string
	DownloadedAt  int64
}

func (q *Queries) GetMediaDownloadInfo(ctx context.Context, arg GetMediaDownloadInfoParams) (GetMediaDownloadInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaDownloadInfo, arg.ChatJid, arg.MsgID)
	var i GetMediaDownloadInfoRow
	err := row.Scan(
		&i.ChatJid,
		&i.Name,
		&i.MsgID,
		&i.MediaType,
		&i.Filename,
		&i.MimeType,
		&i.DirectPath,
		&i.MediaKey,
		&i.FileSha256,
		&i.FileEncSha256,
		&i.FileLength,
		&i.LocalPath,
		&i.DownloadedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT m.rowid, m.chat_jid, COALESCE(c.name,''), m.msg_id, COALESCE(m.sender_jid,''), COALESCE(m.sender_name,''), m.ts, m.from_me, COALESCE(m.text,''), COALESCE(m.display_text,''), COALESCE(m.quoted_msg_id,''), COALESCE(m.quoted_sender_jid,''), m.is_forwarded, m.forwarding_score, COALESCE(m.reaction_to_id,''), COALESCE(m.reaction_emoji,''), COALESCE(m.media_type,''), COALESCE(m.media_caption,''), COALESCE(m.filename,''), COALESCE(m.mime_type,''), COALESCE(m.direct_path,''), COALESCE(m.local_path,''), COALESCE(m.downloaded_at,0), CASE WHEN s.msg_id IS NULL THEN 0 ELSE 1 END, COALESCE(s.starred_at,0), m.revoked, m.deleted_for_me, COALESCE(m.deleted_at,0), COALESCE(m.deletion_reason,''), COALESCE(m.payload_purged_at,0), m.edited, COALESCE(m.buttons,''), ''
FROM messages m
LEFT JOIN chats c ON c.jid = m.chat_jid
LEFT JOIN starred s ON s.chat_jid = m.chat_jid AND s.msg_id = m.msg_id
WHERE m.chat_jid = ? AND m.msg_id = ?
`

type GetMessageParams struct {
	ChatJid string
	MsgID   string
}

type GetMessageRow struct {
	Rowid           int64
	ChatJid         string
	Name            string
	MsgID           string
	SenderJid       string
	SenderName      string
	Ts              int64
	FromMe          int64
	Text            string
	DisplayText     string
	QuotedMsgID     string
	QuotedSenderJid string
	IsForwarded     int64
	ForwardingScore int64
	ReactionToID    string
	ReactionEmoji   string
	MediaType       string
	MediaCaption    string
	Filename        string
	MimeType        string
	DirectPath      string
	LocalPath       string
	DownloadedAt    int64
	Column24        int64
	StarredAt       int64
	Revoked         int64
	DeletedForMe    int64
	DeletedAt       int64
	DeletionReason  string
	PayloadPurgedAt int64
	Edited          int64
	Buttons         string
	Column33        string
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getMessage, arg.ChatJid, arg.MsgID)
	var i GetMessageRow
	err := row.Scan(
		&i.Rowid,
		&i.ChatJid,
		&i.Name,
		&i.MsgID,
		&i.SenderJid,
		&i.SenderName,
		&i.Ts,
		&i.FromMe,
		&i.Text,
		&i.DisplayText,
		&i.QuotedMsgID,
		&i.QuotedSenderJid,
		&i.IsForwarded,
		&i.ForwardingScore,
		&i.ReactionToID,
		&i.ReactionEmoji,
		&i.MediaType,
		&i.MediaCaption,
		&i.Filename,
		&i.MimeType,
		&i.DirectPath,
		&i.LocalPath,
		&i.DownloadedAt,
		&i.Column24,
		&i.StarredAt,
		&i.Revoked,
		&i.DeletedForMe,
		&i.DeletedAt,
		&i.DeletionReason,
		&i.PayloadPurgedAt,
		&i.Edited,
		&i.Buttons,
		&i.Column33,
	)
	return i, err
}

const getMessageLocation = `-- name: GetMessageLocation :one
SELECT chat_jid, msg_id, latitude, longitude, COALESCE(name,''), COALESCE(address,''), is_live
FROM message_locations
WHERE chat_jid = ? AND msg_id = ?
`

type GetMessageLocationParams struct {
	ChatJid string
	MsgID   string
}

type GetMessageLocationRow struct {
	ChatJid   string
	MsgID     string
	Latitude  float64
	Longitude float64
	Name      string
	Address   string
	IsLive    int64
}

func (q *Queries) GetMessageLocation(ctx context.Context, arg GetMessageLocationParams) (GetMessageLocationRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageLocation, arg.ChatJid, arg.MsgID)
	var i GetMessageLocationRow
	err := row.Scan(
		&i.ChatJid,
		&i.MsgID,
		&i.Latitude,
		&i.Longitude,
		&i.Name,
		&i.Address,
		&i.IsLive,
	)
	return i, err
}

const getNextMessageInfo = `-- name: GetNextMessageInfo :one
SELECT m.chat_jid, m.msg_id, m.ts, m.from_me, COALESCE(m.sender_jid,''), COALESCE(m.sender_name,'')
FROM messages m
JOIN messages anchor ON anchor.chat_jid = m.chat_jid
WHERE anchor.chat_jid = ? AND anchor.msg_id = ?
  AND (m.ts, m.rowid) > (anchor.ts, anchor.rowid)
ORDER BY m.ts ASC, m.rowid ASC
LIMIT 1
`

type GetNextMessageInfoParams struct {
	ChatJid string
	MsgID   string
}

type GetNextMessageInfoRow struct {
	ChatJid    string
	MsgID      string
	Ts         int64
	FromMe     int64
	SenderJid  string
	SenderName string
}

func (q *Queries) GetNextMessageInfo(ctx context.Context, arg GetNextMessageInfoParams) (GetNextMessageInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getNextMessageInfo, arg.ChatJid, arg.MsgID)
	var i GetNextMessageInfoRow
	err := row.Scan(
		&i.ChatJid,
		&i.MsgID,
		&i.Ts,
		&i.FromMe,
		&i.SenderJid,
		&i.SenderName,
	)
	return i, err
}

const getOldestMessageInfo = `-- name: GetOldestMessageInfo :one
SELECT m.chat_jid, m.msg_id, m.ts, m.from_me, COALESCE(m.sender_jid,''), COALESCE(m.sender_name,'')
FROM messages m
WHERE m.chat_jid = ?
ORDER BY m.ts ASC, m.rowid ASC
LIMIT 1
`

type GetOldestMessageInfoRow struct {
	ChatJid    string
	MsgID      string
	Ts         int64
	FromMe     int64
	SenderJid  string
	SenderName string
}

func (q *Queries) GetOldestMessageInfo(ctx context.Context, chatJid string) (GetOldestMessageInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getOldestMessageInfo, chatJid)
	var i GetOldestMessageInfoRow
	err := row.Scan(
		&i.ChatJid,
		&i.MsgID,
		&i.Ts,
		&i.FromMe,
		&i.SenderJid,
		&i.SenderName,
	)
	return i, err
}

const getPoll = `-- name: GetPoll :one
SELECT p.chat_jid, p.msg_id, COALESCE(p.sender_jid,''), p.question, p.options_json, p.selectable_count, p.created_ts
FROM polls p
LEFT JOIN messages m ON m.chat_jid = p.chat_jid AND m.msg_id = p.msg_id
WHERE p.chat_jid = ? AND p.msg_id = ?
  AND (m.msg_id IS NULL OR m.deleted_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM message_payload_purges x WHERE x.chat_jid = p.chat_jid AND x.msg_id = p.msg_id)
`

type GetPollParams struct {
	ChatJid string
	MsgID   string
}

type GetPollRow struct {
	ChatJid         string
	MsgID           string
	SenderJid       string
	Question        string
	OptionsJson     string
	SelectableCount int64
	CreatedTs       int64
}

func (q *Queries) GetPoll(ctx context.Context, arg GetPollParams) (GetPollRow, error) {
	row := q.db.QueryRowContext(ctx, getPoll, arg.ChatJid, arg.MsgID)
	var i GetPollRow
	err := row.Scan(
		&i.ChatJid,
		&i.MsgID,
		&i.SenderJid,
		&i.Question,
		&i.OptionsJson,
		&i.SelectableCount,
		&i.CreatedTs,
	)
	return i, err
}

const insertGroupParticipant = `-- name: InsertGroupParticipant :exec
INSERT INTO group_participants(group_jid, user_jid, role, updated_at)
VALUES(?, ?, ?, ?)
`

type InsertGroupParticipantParams struct {
	GroupJid  string
	UserJid   string
	Role      sql.NullString
	UpdatedAt int64
}

func (q *Queries) InsertGroupParticipant(ctx context.Context, arg InsertGroupParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupParticipant,
		arg.GroupJid,
		arg.UserJid,
		arg.Role,
		arg.UpdatedAt,
	)
	return err
}

const listContacts = `-- name: ListContacts :many
SELECT c.jid,
       COALESCE(c.phone,'') AS phone,
       COALESCE(NULLIF(a.alias,''), '') AS alias,
       COALESCE(NULLIF(c.system_name,''), '') AS system_name,
       COALESCE(NULLIF(a.alias,''), NULLIF(c.system_name,''), NULLIF(c.full_name,''), NULLIF(c.push_name,''), NULLIF(c.business_name,''), NULLIF(c.first_name,''), '') AS name,
       c.updated_at
FROM contacts c
LEFT JOIN contact_aliases a ON a.jid = c.jid
ORDER BY COALESCE(NULLIF(a.alias,''), NULLIF(c.system_name,''), NULLIF(c.full_name,''), NULLIF(c.push_name,''), NULLIF(c.business_name,''), NULLIF(c.first_name,''), c.jid)
LIMIT ?
`

type ListContactsRow struct {
	Jid        string
	Phone      string
	Alias      interface{}
	SystemName interface{}
	Name       interface{}
	UpdatedAt  int64
}

func (q *Queries) ListContacts(ctx context.Context, limit int64) ([]ListContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContacts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Phone,
			&i.Alias,
			&i.SystemName,
			&i.Name,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupParticipants = `-- name: ListGroupParticipants :many
SELECT group_jid, user_jid, COALESCE(role, 'member') AS role, updated_at
FROM group_participants
WHERE group_jid = ?
ORDER BY CASE role
    WHEN 'superadmin' THEN 1
    WHEN 'admin' THEN 2
    ELSE 3
END, user_jid ASC
`

type ListGroupParticipantsRow struct {
	GroupJid  string
	UserJid   string
	Role      string
	UpdatedAt int64
}

func (q *Queries) ListGroupParticipants(ctx context.Context, groupJid string) ([]ListGroupParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupParticipants, groupJid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupParticipantsRow
	for rows.Next() {
		var i ListGroupParticipantsRow
		if err := rows.Scan(
			&i.GroupJid,
			&i.UserJid,
			&i.Role,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinedGroupJIDs = `-- name: ListJoinedGroupJIDs :many
SELECT jid FROM groups WHERE left_at IS NULL
`

func (q *Queries) ListJoinedGroupJIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listJoinedGroupJIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jid string
		if err := rows.Scan(&jid); err != nil {
			return nil, err
		}
		items = append(items, jid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeftGroups = `-- name: ListLeftGroups :many
SELECT jid, COALESCE(name,''), COALESCE(owner_jid,''), is_parent, COALESCE(linked_parent_jid,''), COALESCE(created_ts,0), COALESCE(left_at,0), updated_at
FROM groups
WHERE left_at IS NOT NULL
ORDER BY left_at DESC
`

type ListLeftGroupsRow struct {
	Jid             string
	Name            string
	OwnerJid        string
	IsParent        int64
	LinkedParentJid string
	CreatedTs       int64
	LeftAt          int64
	UpdatedAt       int64
}

func (q *Queries) ListLeftGroups(ctx context.Context) ([]ListLeftGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLeftGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeftGroupsRow
	for rows.Next() {
		var i ListLeftGroupsRow
		if err := rows.Scan(
			&i.Jid,
			&i.Name,
			&i.OwnerJid,
			&i.IsParent,
			&i.LinkedParentJid,
			&i.CreatedTs,
			&i.LeftAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMediaBefore = `-- name: ListPendingMediaBefore :many
SELECT m.chat_jid, m.msg_id
FROM messages m
WHERE COALESCE(m.media_type,'') != ''
  AND COALESCE(m.direct_path,'') != ''
  AND m.media_key IS NOT NULL AND length(m.media_key) > 0
  AND COALESCE(m.local_path,'') = ''
  AND m.deleted_at IS NULL
  AND m.media_unavailable_at IS NULL
  AND m.ts < ?1
  AND (?2 = '' OR m.chat_jid = ?2)
ORDER BY m.ts DESC, m.rowid DESC
LIMIT CASE WHEN ?3 <= 0 THEN -1 ELSE ?3 END
`

type ListPendingMediaBeforeParams struct {
	BeforeTs   int64
	ChatJid    interface{}
	LimitCount interface{}
}

type ListPendingMediaBeforeRow struct {
	ChatJid string
	MsgID   string
}

func (q *Queries) ListPendingMediaBefore(ctx context.Context, arg ListPendingMediaBeforeParams) ([]ListPendingMediaBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMediaBefore, arg.BeforeTs, arg.ChatJid, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMediaBeforeRow
	for rows.Next() {
		var i ListPendingMediaBeforeRow
		if err := rows.Scan(&i.ChatJid, &i.MsgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMediaDownloads = `-- name: ListPendingMediaDownloads :many
SELECT m.chat_jid, m.msg_id
FROM messages m
WHERE COALESCE(m.media_type,'') != ''
  AND COALESCE(m.direct_path,'') != ''
  AND m.media_key IS NOT NULL AND length(m.media_key) > 0
  AND COALESCE(m.local_path,'') = ''
  AND m.deleted_at IS NULL
  AND m.media_unavailable_at IS NULL
  AND (?1 = '' OR m.chat_jid = ?1)
ORDER BY m.ts DESC, m.rowid DESC
LIMIT CASE WHEN ?2 <= 0 THEN -1 ELSE ?2 END
`

type ListPendingMediaDownloadsParams struct {
	ChatJid    interface{}
	LimitCount interface{}
}

type ListPendingMediaDownloadsRow struct {
	ChatJid string
	MsgID   string
}

func (q *Queries) ListPendingMediaDownloads(ctx context.Context, arg ListPendingMediaDownloadsParams) ([]ListPendingMediaDownloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMediaDownloads, arg.ChatJid, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMediaDownloadsRow
	for rows.Next() {
		var i ListPendingMediaDownloadsRow
		if err := rows.Scan(&i.ChatJid, &i.MsgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollVotes = `-- name: ListPollVotes :many
SELECT pv.chat_jid, pv.poll_msg_id, pv.voter_jid, pv.vote_msg_id, pv.selected_options_json, pv.ts
FROM poll_votes pv
WHERE pv.chat_jid = ? AND pv.poll_msg_id = ?
  AND NOT EXISTS (
      SELECT 1 FROM message_payload_purges p
      WHERE p.chat_jid = pv.chat_jid
        AND (p.msg_id = pv.poll_msg_id OR p.msg_id = pv.vote_msg_id)
  )
ORDER BY pv.ts ASC, pv.voter_jid ASC
`

type ListPollVotesParams struct {
	ChatJid   string
	PollMsgID string
}

func (q *Queries) ListPollVotes(ctx context.Context, arg ListPollVotesParams) ([]PollVote, error) {
	rows, err := q.db.QueryContext(ctx, listPollVotes, arg.ChatJid, arg.PollMsgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollVote
	for rows.Next() {
		var i PollVote
		if err := rows.Scan(
			&i.ChatJid,
			&i.PollMsgID,
			&i.VoterJid,
			&i.VoteMsgID,
			&i.SelectedOptionsJson,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolls = `-- name: ListPolls :many
SELECT p.chat_jid, p.msg_id, COALESCE(p.sender_jid,''), p.question, p.options_json, p.selectable_count, p.created_ts
FROM polls p
LEFT JOIN messages m ON m.chat_jid = p.chat_jid AND m.msg_id = p.msg_id
WHERE (m.msg_id IS NULL OR m.deleted_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM message_payload_purges x WHERE x.chat_jid = p.chat_jid AND x.msg_id = p.msg_id)
  AND (? = '' OR p.chat_jid = ?)
ORDER BY p.created_ts DESC, p.msg_id DESC
LIMIT ? OFFSET ?
`

type ListPollsParams struct {
	Column1 interface{}
	ChatJid string
	Limit   int64
	Offset  int64
}

type ListPollsRow struct {
	ChatJid         string
	MsgID           string
	SenderJid       string
	Question        string
	OptionsJson     string
	SelectableCount int64
	CreatedTs       int64
}

func (q *Queries) ListPolls(ctx context.Context, arg ListPollsParams) ([]ListPollsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPolls,
		arg.Column1,
		arg.ChatJid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPollsRow
	for rows.Next() {
		var i ListPollsRow
		if err := rows.Scan(
			&i.ChatJid,
			&i.MsgID,
			&i.SenderJid,
			&i.Question,
			&i.OptionsJson,
			&i.SelectableCount,
			&i.CreatedTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT tag FROM contact_tags WHERE jid = ? ORDER BY tag
`

func (q *Queries) ListTags(ctx context.Context, jid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTags, jid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGroupLeft = `-- name: MarkGroupLeft :exec
UPDATE groups SET left_at = ?, updated_at = ? WHERE jid = ?
`

type MarkGroupLeftParams struct {
	LeftAt    sql.NullInt64
	UpdatedAt int64
	Jid       string
}

func (q *Queries) MarkGroupLeft(ctx context.Context, arg MarkGroupLeftParams) error {
	_, err := q.db.ExecContext(ctx, markGroupLeft, arg.LeftAt, arg.UpdatedAt, arg.Jid)
	return err
}

const markMediaDownloaded = `-- name: MarkMediaDownloaded :exec
UPDATE messages SET local_path = ?, downloaded_at = ?, media_unavailable_at = NULL WHERE chat_jid = ? AND msg_id = ?
`

type MarkMediaDownloadedParams struct {
	LocalPath    sql.NullString
	DownloadedAt sql.NullInt64
	ChatJid      string
	MsgID        string
}

func (q *Queries) MarkMediaDownloaded(ctx context.Context, arg MarkMediaDownloadedParams) error {
	_, err := q.db.ExecContext(ctx, markMediaDownloaded,
		arg.LocalPath,
		arg.DownloadedAt,
		arg.ChatJid,
		arg.MsgID,
	)
	return err
}

const markMediaUnavailable = `-- name: MarkMediaUnavailable :exec
UPDATE messages SET media_unavailable_at = ? WHERE chat_jid = ? AND msg_id = ?
`

type MarkMediaUnavailableParams struct {
	MediaUnavailableAt sql.NullInt64
	ChatJid            string
	MsgID              string
}

func (q *Queries) MarkMediaUnavailable(ctx context.Context, arg MarkMediaUnavailableParams) error {
	_, err := q.db.ExecContext(ctx, markMediaUnavailable, arg.MediaUnavailableAt, arg.ChatJid, arg.MsgID)
	return err
}

const markMessageDeletedForMe = `-- name: MarkMessageDeletedForMe :execrows
UPDATE messages
SET deleted_for_me = 1,
    deleted_at = COALESCE(deleted_at, ?),
    deletion_reason = CASE WHEN deleted_at IS NULL THEN ? ELSE deletion_reason END,
    edited = 0,
    edited_ts = 0
WHERE chat_jid = ? AND msg_id = ?
`

type MarkMessageDeletedForMeParams struct {
	DeletedAt      sql.NullInt64
	DeletionReason sql.NullString
	ChatJid        string
	MsgID          string
}

func (q *Queries) MarkMessageDeletedForMe(ctx context.Context, arg MarkMessageDeletedForMeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageDeletedForMe,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.ChatJid,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessageDeletedForMePreserveMedia = `-- name: MarkMessageDeletedForMePreserveMedia :execrows
UPDATE messages
SET deleted_for_me = 1,
    deleted_at = COALESCE(deleted_at, ?),
    deletion_reason = CASE WHEN deleted_at IS NULL THEN ? ELSE deletion_reason END
WHERE chat_jid = ? AND msg_id = ?
`

type MarkMessageDeletedForMePreserveMediaParams struct {
	DeletedAt      sql.NullInt64
	DeletionReason sql.NullString
	ChatJid        string
	MsgID          string
}

func (q *Queries) MarkMessageDeletedForMePreserveMedia(ctx context.Context, arg MarkMessageDeletedForMePreserveMediaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageDeletedForMePreserveMedia,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.ChatJid,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMessageRevoked = `-- name: MarkMessageRevoked :execrows
UPDATE messages
SET revoked = 1,
    deleted_at = COALESCE(deleted_at, ?),
    deletion_reason = CASE WHEN deleted_at IS NULL THEN ? ELSE deletion_reason END,
    edited = 0,
    edited_ts = 0
WHERE chat_jid = ? AND msg_id = ?
`

type MarkMessageRevokedParams struct {
	DeletedAt      sql.NullInt64
	DeletionReason sql.NullString
	ChatJid        string
	MsgID          string
}

func (q *Queries) MarkMessageRevoked(ctx context.Context, arg MarkMessageRevokedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMessageRevoked,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.ChatJid,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const messageContextAfter = `-- name: MessageContextAfter :many
SELECT m.rowid, m.chat_jid, COALESCE(c.name,''), m.msg_id, COALESCE(m.sender_jid,''), COALESCE(m.sender_name,''), m.ts, m.from_me, COALESCE(m.text,''), COALESCE(m.display_text,''), COALESCE(m.quoted_msg_id,''), COALESCE(m.quoted_sender_jid,''), m.is_forwarded, m.forwarding_score, COALESCE(m.reaction_to_id,''), COALESCE(m.reaction_emoji,''), COALESCE(m.media_type,''), COALESCE(m.media_caption,''), COALESCE(m.filename,''), COALESCE(m.mime_type,''), COALESCE(m.direct_path,''), COALESCE(m.local_path,''), COALESCE(m.downloaded_at,0), CASE WHEN s.msg_id IS NULL THEN 0 ELSE 1 END, COALESCE(s.starred_at,0), m.revoked, m.deleted_for_me, COALESCE(m.deleted_at,0), COALESCE(m.deletion_reason,''), COALESCE(m.payload_purged_at,0), m.edited, COALESCE(m.buttons,''), ''
FROM messages m
LEFT JOIN chats c ON c.jid = m.chat_jid
LEFT JOIN starred s ON s.chat_jid = m.chat_jid AND s.msg_id = m.msg_id
WHERE m.chat_jid = ? AND m.deleted_at IS NULL AND (m.ts > ? OR (m.ts = ? AND m.rowid > ?))
ORDER BY m.ts ASC, m.rowid ASC
LIMIT ?
`

type MessageContextAfterParams struct {
	ChatJid string
	Ts      int64
	Ts_2    int64
	Rowid   int64
	Limit   int64
}

type MessageContextAfterRow struct {
	Rowid           int64
	ChatJid         string
	Name            string
	MsgID           string
	SenderJid       string
	SenderName      string
	Ts              int64
	FromMe          int64
	Text            string
	DisplayText     string
	QuotedMsgID     string
	QuotedSenderJid string
	IsForwarded     int64
	ForwardingScore int64
	ReactionToID    string
	ReactionEmoji   string
	MediaType       string
	MediaCaption    string
	Filename        string
	MimeType        string
	DirectPath      string
	LocalPath       string
	DownloadedAt    int64
	Column24        int64
	StarredAt       int64
	Revoked         int64
	DeletedForMe    int64
	DeletedAt       int64
	DeletionReason  string
	PayloadPurgedAt int64
	Edited          int64
	Buttons         string
	Column33        string
}

func (q *Queries) MessageContextAfter(ctx context.Context, arg MessageContextAfterParams) ([]MessageContextAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, messageContextAfter,
		arg.ChatJid,
		arg.Ts,
		arg.Ts_2,
		arg.Rowid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageContextAfterRow
	for rows.Next() {
		var i MessageContextAfterRow
		if err := rows.Scan(
			&i.Rowid,
			&i.ChatJid,
			&i.Name,
			&i.MsgID,
			&i.SenderJid,
			&i.SenderName,
			&i.Ts,
			&i.FromMe,
			&i.Text,
			&i.DisplayText,
			&i.QuotedMsgID,
			&i.QuotedSenderJid,
			&i.IsForwarded,
			&i.ForwardingScore,
			&i.ReactionToID,
			&i.ReactionEmoji,
			&i.MediaType,
			&i.MediaCaption,
			&i.Filename,
			&i.MimeType,
			&i.DirectPath,
			&i.LocalPath,
			&i.DownloadedAt,
			&i.Column24,
			&i.StarredAt,
			&i.Revoked,
			&i.DeletedForMe,
			&i.DeletedAt,
			&i.DeletionReason,
			&i.PayloadPurgedAt,
			&i.Edited,
			&i.Buttons,
			&i.Column33,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageContextBefore = `-- name: MessageContextBefore :many
SELECT m.rowid, m.chat_jid, COALESCE(c.name,''), m.msg_id, COALESCE(m.sender_jid,''), COALESCE(m.sender_name,''), m.ts, m.from_me, COALESCE(m.text,''), COALESCE(m.display_text,''), COALESCE(m.quoted_msg_id,''), COALESCE(m.quoted_sender_jid,''), m.is_forwarded, m.forwarding_score, COALESCE(m.reaction_to_id,''), COALESCE(m.reaction_emoji,''), COALESCE(m.media_type,''), COALESCE(m.media_caption,''), COALESCE(m.filename,''), COALESCE(m.mime_type,''), COALESCE(m.direct_path,''), COALESCE(m.local_path,''), COALESCE(m.downloaded_at,0), CASE WHEN s.msg_id IS NULL THEN 0 ELSE 1 END, COALESCE(s.starred_at,0), m.revoked, m.deleted_for_me, COALESCE(m.deleted_at,0), COALESCE(m.deletion_reason,''), COALESCE(m.payload_purged_at,0), m.edited, COALESCE(m.buttons,''), ''
FROM messages m
LEFT JOIN chats c ON c.jid = m.chat_jid
LEFT JOIN starred s ON s.chat_jid = m.chat_jid AND s.msg_id = m.msg_id
WHERE m.chat_jid = ? AND m.deleted_at IS NULL AND (m.ts < ? OR (m.ts = ? AND m.rowid < ?))
ORDER BY m.ts DESC, m.rowid DESC
LIMIT ?
`

type MessageContextBeforeParams struct {
	ChatJid string
	Ts      int64
	Ts_2    int64
	Rowid   int64
	Limit   int64
}

type MessageContextBeforeRow struct {
	Rowid           int64
	ChatJid         string
	Name            string
	MsgID           string
	SenderJid       string
	SenderName      string
	Ts              int64
	FromMe          int64
	Text            string
	DisplayText     string
	QuotedMsgID     string
	QuotedSenderJid string
	IsForwarded     int64
	ForwardingScore int64
	ReactionToID    string
	ReactionEmoji   string
	MediaType       string
	MediaCaption    string
	Filename        string
	MimeType        string
	DirectPath      string
	LocalPath       string
	DownloadedAt    int64
	Column24        int64
	StarredAt       int64
	Revoked         int64
	DeletedForMe    int64
	DeletedAt       int64
	DeletionReason  string
	PayloadPurgedAt int64
	Edited          int64
	Buttons         string
	Column33        string
}

func (q *Queries) MessageContextBefore(ctx context.Context, arg MessageContextBeforeParams) ([]MessageContextBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, messageContextBefore,
		arg.ChatJid,
		arg.Ts,
		arg.Ts_2,
		arg.Rowid,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageContextBeforeRow
	for rows.Next() {
		var i MessageContextBeforeRow
		if err := rows.Scan(
			&i.Rowid,
			&i.ChatJid,
			&i.Name,
			&i.MsgID,
			&i.SenderJid,
			&i.SenderName,
			&i.Ts,
			&i.FromMe,
			&i.Text,
			&i.DisplayText,
			&i.QuotedMsgID,
			&i.QuotedSenderJid,
			&i.IsForwarded,
			&i.ForwardingScore,
			&i.ReactionToID,
			&i.ReactionEmoji,
			&i.MediaType,
			&i.MediaCaption,
			&i.Filename,
			&i.MimeType,
			&i.DirectPath,
			&i.LocalPath,
			&i.DownloadedAt,
			&i.Column24,
			&i.StarredAt,
			&i.Revoked,
			&i.DeletedForMe,
			&i.DeletedAt,
			&i.DeletionReason,
			&i.PayloadPurgedAt,
			&i.Edited,
			&i.Buttons,
			&i.Column33,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollOptions = `-- name: PollOptions :one
SELECT options_json FROM polls WHERE chat_jid = ? AND msg_id = ?
`

type PollOptionsParams struct {
	ChatJid string
	MsgID   string
}

func (q *Queries) PollOptions(ctx context.Context, arg PollOptionsParams) (string, error) {
	row := q.db.QueryRowContext(ctx, pollOptions, arg.ChatJid, arg.MsgID)
	var options_json string
	err := row.Scan(&options_json)
	return options_json, err
}

const removeAlias = `-- name: RemoveAlias :exec
DELETE FROM contact_aliases WHERE jid = ?
`

func (q *Queries) RemoveAlias(ctx context.Context, jid string) error {
	_, err := q.db.ExecContext(ctx, removeAlias, jid)
	return err
}

const removeTag = `-- name: RemoveTag :exec
DELETE FROM contact_tags WHERE jid = ? AND tag = ?
`

type RemoveTagParams struct {
	Jid string
	Tag string
}

func (q *Queries) RemoveTag(ctx context.Context, arg RemoveTagParams) error {
	_, err := q.db.ExecContext(ctx, removeTag, arg.Jid, arg.Tag)
	return err
}

const setAlias = `-- name: SetAlias :exec
INSERT INTO contact_aliases(jid, alias, notes, updated_at)
VALUES (?, ?, NULL, ?)
ON CONFLICT(jid) DO UPDATE SET alias=excluded.alias, updated_at=excluded.updated_at
`

type SetAliasParams struct {
	Jid       string
	Alias     string
	UpdatedAt int64
}

func (q *Queries) SetAlias(ctx context.Context, arg SetAliasParams) error {
	_, err := q.db.ExecContext(ctx, setAlias, arg.Jid, arg.Alias, arg.UpdatedAt)
	return err
}

const setChatArchived = `-- name: SetChatArchived :exec
INSERT INTO chats(jid, kind, archived)
VALUES(?, 'unknown', ?)
ON CONFLICT(jid) DO UPDATE SET archived=excluded.archived
`

type SetChatArchivedParams struct {
	Jid      string
	Archived int64
}

func (q *Queries) SetChatArchived(ctx context.Context, arg SetChatArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setChatArchived, arg.Jid, arg.Archived)
	return err
}

const setChatArchivedAndUnpin = `-- name: SetChatArchivedAndUnpin :exec
INSERT INTO chats(jid, kind, archived)
VALUES(?, 'unknown', ?)
ON CONFLICT(jid) DO UPDATE SET archived=excluded.archived, pinned=0
`

type SetChatArchivedAndUnpinParams struct {
	Jid      string
	Archived int64
}

func (q *Queries) SetChatArchivedAndUnpin(ctx context.Context, arg SetChatArchivedAndUnpinParams) error {
	_, err := q.db.ExecContext(ctx, setChatArchivedAndUnpin, arg.Jid, arg.Archived)
	return err
}

const setChatMutedUntil = `-- name: SetChatMutedUntil :exec
INSERT INTO chats(jid, kind, muted_until)
VALUES(?, 'unknown', ?)
ON CONFLICT(jid) DO UPDATE SET muted_until=excluded.muted_until
`

type SetChatMutedUntilParams struct {
	Jid        string
	MutedUntil int64
}

func (q *Queries) SetChatMutedUntil(ctx context.Context, arg SetChatMutedUntilParams) error {
	_, err := q.db.ExecContext(ctx, setChatMutedUntil, arg.Jid, arg.MutedUntil)
	return err
}

const setChatPinned = `-- name: SetChatPinned :exec
INSERT INTO chats(jid, kind, pinned)
VALUES(?, 'unknown', ?)
ON CONFLICT(jid) DO UPDATE SET pinned=excluded.pinned
`

type SetChatPinnedParams struct {
	Jid    string
	Pinned int64
}

func (q *Queries) SetChatPinned(ctx context.Context, arg SetChatPinnedParams) error {
	_, err := q.db.ExecContext(ctx, setChatPinned, arg.Jid, arg.Pinned)
	return err
}

const setStarredDelete = `-- name: SetStarredDelete :exec
DELETE FROM starred WHERE chat_jid = ? AND msg_id = ?
`

type SetStarredDeleteParams struct {
	ChatJid string
	MsgID   string
}

func (q *Queries) SetStarredDelete(ctx context.Context, arg SetStarredDeleteParams) error {
	_, err := q.db.ExecContext(ctx, setStarredDelete, arg.ChatJid, arg.MsgID)
	return err
}

const setStarredUpsert = `-- name: SetStarredUpsert :exec
INSERT INTO starred(chat_jid, msg_id, sender_jid, from_me, starred_at)
VALUES(?, ?, ?, ?, ?)
ON CONFLICT(chat_jid, msg_id) DO UPDATE SET
    sender_jid=COALESCE(NULLIF(excluded.sender_jid,''), starred.sender_jid),
    from_me=excluded.from_me,
    starred_at=excluded.starred_at
`

type SetStarredUpsertParams struct {
	ChatJid   string
	MsgID     string
	SenderJid sql.NullString
	FromMe    int64
	StarredAt int64
}

func (q *Queries) SetStarredUpsert(ctx context.Context, arg SetStarredUpsertParams) error {
	_, err := q.db.ExecContext(ctx, setStarredUpsert,
		arg.ChatJid,
		arg.MsgID,
		arg.SenderJid,
		arg.FromMe,
		arg.StarredAt,
	)
	return err
}

const setSystemName = `-- name: SetSystemName :execrows
UPDATE contacts SET system_name = ?, updated_at = ? WHERE jid = ?
`

type SetSystemNameParams struct {
	SystemName sql.NullString
	UpdatedAt  int64
	Jid        string
}

func (q *Queries) SetSystemName(ctx context.Context, arg SetSystemNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSystemName, arg.SystemName, arg.UpdatedAt, arg.Jid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const stats = `-- name: Stats :one
SELECT
    (SELECT COUNT(*) FROM messages),
    (SELECT COUNT(*) FROM chats),
    (SELECT COUNT(*) FROM contacts),
    (SELECT COUNT(*) FROM groups),
    COALESCE((SELECT MAX(ts) FROM messages), 0)
`

type StatsRow struct {
	Count    int64
	Count_2  int64
	Count_3  int64
	Count_4  int64
	Coalesce interface{}
}

func (q *Queries) Stats(ctx context.Context) (StatsRow, error) {
	row := q.db.QueryRowContext(ctx, stats)
	var i StatsRow
	err := row.Scan(
		&i.Count,
		&i.Count_2,
		&i.Count_3,
		&i.Count_4,
		&i.Coalesce,
	)
	return i, err
}

const updateMessageText = `-- name: UpdateMessageText :execrows
UPDATE messages
SET text = ?,
    display_text = ?,
    buttons = NULL,
    media_type = NULL,
    media_caption = NULL,
    filename = NULL,
    mime_type = NULL,
    direct_path = NULL,
    media_key = NULL,
    file_sha256 = NULL,
    file_enc_sha256 = NULL,
    file_length = NULL,
    local_path = NULL,
    downloaded_at = NULL,
    edited = 1,
    edited_ts = strftime('%s', 'now')
WHERE chat_jid = ? AND msg_id = ? AND deleted_at IS NULL
`

type UpdateMessageTextParams struct {
	Text        sql.NullString
	DisplayText sql.NullString
	ChatJid     string
	MsgID       string
}

func (q *Queries) UpdateMessageText(ctx context.Context, arg UpdateMessageTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMessageText,
		arg.Text,
		arg.DisplayText,
		arg.ChatJid,
		arg.MsgID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertChat = `-- name: UpsertChat :exec
INSERT INTO chats(jid, kind, name, last_message_ts)
VALUES(?, ?, ?, ?)
ON CONFLICT(jid) DO UPDATE SET
    kind=excluded.kind,
    name=CASE WHEN excluded.name IS NOT NULL AND excluded.name != '' THEN excluded.name ELSE chats.name END,
    last_message_ts=CASE WHEN excluded.last_message_ts > COALESCE(chats.last_message_ts, 0) THEN excluded.last_message_ts ELSE chats.last_message_ts END
`

type UpsertChatParams struct {
	Jid           string
	Kind          string
	Name          sql.NullString
	LastMessageTs sql.NullInt64
}

func (q *Queries) UpsertChat(ctx context.Context, arg UpsertChatParams) error {
	_, err := q.db.ExecContext(ctx, upsertChat,
		arg.Jid,
		arg.Kind,
		arg.Name,
		arg.LastMessageTs,
	)
	return err
}

const upsertChatMetadata = `-- name: UpsertChatMetadata :exec
INSERT INTO chats(jid, kind, name)
VALUES(?, ?, ?)
ON CONFLICT(jid) DO UPDATE SET
    kind=excluded.kind,
    name=CASE WHEN excluded.name IS NOT NULL AND excluded.name != '' THEN excluded.name ELSE chats.name END
`

type UpsertChatMetadataParams struct {
	Jid  string
	Kind string
	Name sql.NullString
}

func (q *Queries) UpsertChatMetadata(ctx context.Context, arg UpsertChatMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertChatMetadata, arg.Jid, arg.Kind, arg.Name)
	return err
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts(jid, phone, push_name, full_name, first_name, business_name, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(jid) DO UPDATE SET
    phone=COALESCE(NULLIF(excluded.phone,''), contacts.phone),
    push_name=COALESCE(NULLIF(excluded.push_name,''), contacts.push_name),
    full_name=COALESCE(NULLIF(excluded.full_name,''), contacts.full_name),
    first_name=COALESCE(NULLIF(excluded.first_name,''), contacts.first_name),
    business_name=COALESCE(NULLIF(excluded.business_name,''), contacts.business_name),
    updated_at=excluded.updated_at
`

type UpsertContactParams struct {
	Jid          string
	Phone        sql.NullString
	PushName     sql.NullString
	FullName     sql.NullString
	FirstName    sql.NullString
	BusinessName sql.NullString
	UpdatedAt    int64
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact,
		arg.Jid,
		arg.Phone,
		arg.PushName,
		arg.FullName,
		arg.FirstName,
		arg.BusinessName,
		arg.UpdatedAt,
	)
	return err
}

const upsertGroup = `-- name: UpsertGroup :exec
INSERT INTO groups(jid, name, owner_jid, created_ts, left_at, updated_at)
VALUES (?, ?, ?, ?, NULL, ?)
ON CONFLICT(jid) DO UPDATE SET
    name=COALESCE(NULLIF(excluded.name,''), groups.name),
    owner_jid=COALESCE(NULLIF(excluded.owner_jid,''), groups.owner_jid),
    created_ts=COALESCE(NULLIF(excluded.created_ts,0), groups.created_ts),
    left_at=NULL,
    updated_at=excluded.updated_at
`

type UpsertGroupParams struct {
	Jid       string
	Name      sql.NullString
	OwnerJid  sql.NullString
	CreatedTs sql.NullInt64
	UpdatedAt int64
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroup,
		arg.Jid,
		arg.Name,
		arg.OwnerJid,
		arg.CreatedTs,
		arg.UpdatedAt,
	)
	return err
}

const upsertGroupWithHierarchy = `-- name: UpsertGroupWithHierarchy :exec
INSERT INTO groups(jid, name, owner_jid, created_ts, is_parent, linked_parent_jid, left_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, NULL, ?)
ON CONFLICT(jid) DO UPDATE SET
    name=COALESCE(NULLIF(excluded.name,''), groups.name),
    owner_jid=COALESCE(NULLIF(excluded.owner_jid,''), groups.owner_jid),
    created_ts=COALESCE(NULLIF(excluded.created_ts,0), groups.created_ts),
    is_parent=excluded.is_parent,
    linked_parent_jid=excluded.linked_parent_jid,
    left_at=NULL,
    updated_at=excluded.updated_at
`

type UpsertGroupWithHierarchyParams struct {
	Jid             string
	Name            sql.NullString
	OwnerJid        sql.NullString
	CreatedTs       sql.NullInt64
	IsParent        int64
	LinkedParentJid sql.NullString
	UpdatedAt       int64
}

func (q *Queries) UpsertGroupWithHierarchy(ctx context.Context, arg UpsertGroupWithHierarchyParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroupWithHierarchy,
		arg.Jid,
		arg.Name,
		arg.OwnerJid,
		arg.CreatedTs,
		arg.IsParent,
		arg.LinkedParentJid,
		arg.UpdatedAt,
	)
	return err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages(
    chat_jid, chat_name, msg_id, sender_jid, sender_name, ts, from_me, text, display_text,
    quoted_msg_id, quoted_sender_jid,
    is_forwarded, forwarding_score, reaction_to_id, reaction_emoji,
    media_type, media_caption, filename, mime_type, direct_path,
    media_key, file_sha256, file_enc_sha256, file_length, revoked, deleted_for_me,
    deleted_at, deletion_reason, edited, edited_ts, buttons
) SELECT
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
WHERE NOT EXISTS (
    SELECT 1 FROM message_payload_purges p WHERE p.chat_jid = ? AND p.msg_id = ?
)
ON CONFLICT(chat_jid, msg_id) DO UPDATE SET
    chat_name=COALESCE(NULLIF(excluded.chat_name,''), messages.chat_name),
    sender_jid=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.sender_jid,''), excluded.sender_jid) WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND messages.revoked = 0 AND messages.deleted_for_me = 0 AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.sender_jid ELSE excluded.sender_jid END,
    sender_name=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.sender_name,''), excluded.sender_name) WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND messages.revoked = 0 AND messages.deleted_for_me = 0 AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.sender_name ELSE COALESCE(NULLIF(excluded.sender_name,''), messages.sender_name) END,
    ts=CASE WHEN messages.deleted_at IS NOT NULL AND excluded.deleted_at IS NULL AND COALESCE(messages.text,'') = '' AND COALESCE(NULLIF(NULLIF(messages.display_text, 'This message was deleted'), 'This message was deleted for me'),'') = '' AND COALESCE(messages.media_type,'') = '' AND COALESCE(messages.quoted_msg_id,'') = '' AND messages.buttons IS NULL THEN excluded.ts WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN messages.ts WHEN excluded.edited != 0 THEN messages.ts WHEN messages.edited != 0 AND excluded.edited = 0 THEN excluded.ts WHEN excluded.ts < messages.ts AND excluded.revoked = 0 AND excluded.deleted_for_me = 0 THEN messages.ts ELSE excluded.ts END,
    from_me=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN CASE WHEN messages.from_me != 0 OR excluded.from_me != 0 THEN 1 ELSE 0 END WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.from_me ELSE excluded.from_me END,
    text=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.text,''), excluded.text) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.text ELSE excluded.text END,
    display_text=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(NULLIF(NULLIF(messages.display_text,''), 'This message was deleted'), 'This message was deleted for me'), excluded.display_text) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.display_text WHEN excluded.display_text IS NOT NULL AND excluded.display_text != '' THEN excluded.display_text ELSE messages.display_text END,
    quoted_msg_id=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.quoted_msg_id,''), excluded.quoted_msg_id) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.quoted_msg_id ELSE COALESCE(NULLIF(excluded.quoted_msg_id,''), messages.quoted_msg_id) END,
    quoted_sender_jid=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.quoted_sender_jid,''), excluded.quoted_sender_jid) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.quoted_sender_jid ELSE COALESCE(NULLIF(excluded.quoted_sender_jid,''), messages.quoted_sender_jid) END,
    is_forwarded=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN CASE WHEN messages.is_forwarded != 0 OR excluded.is_forwarded != 0 THEN 1 ELSE 0 END WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND messages.revoked = 0 AND messages.deleted_for_me = 0 AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.is_forwarded ELSE excluded.is_forwarded END,
    forwarding_score=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN max(messages.forwarding_score, excluded.forwarding_score) WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND messages.revoked = 0 AND messages.deleted_for_me = 0 AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.forwarding_score ELSE excluded.forwarding_score END,
    reaction_to_id=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.reaction_to_id,''), excluded.reaction_to_id) WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND messages.revoked = 0 AND messages.deleted_for_me = 0 AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.reaction_to_id ELSE COALESCE(NULLIF(excluded.reaction_to_id,''), messages.reaction_to_id) END,
    reaction_emoji=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.reaction_emoji,''), excluded.reaction_emoji) WHEN (((messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts)) AND messages.revoked = 0 AND messages.deleted_for_me = 0 AND excluded.revoked = 0 AND excluded.deleted_for_me = 0) THEN messages.reaction_emoji ELSE COALESCE(NULLIF(excluded.reaction_emoji,''), messages.reaction_emoji) END,
    media_type=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.media_type,''), excluded.media_type) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.media_type ELSE excluded.media_type END,
    media_caption=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.media_caption,''), excluded.media_caption) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.media_caption ELSE excluded.media_caption END,
    filename=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.filename,''), excluded.filename) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.filename ELSE COALESCE(NULLIF(excluded.filename,''), messages.filename) END,
    mime_type=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.mime_type,''), excluded.mime_type) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.mime_type ELSE COALESCE(NULLIF(excluded.mime_type,''), messages.mime_type) END,
    direct_path=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.direct_path,''), excluded.direct_path) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.direct_path ELSE COALESCE(NULLIF(excluded.direct_path,''), messages.direct_path) END,
    media_key=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN CASE WHEN messages.media_key IS NOT NULL AND length(messages.media_key)>0 THEN messages.media_key ELSE excluded.media_key END WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.media_key WHEN excluded.media_key IS NOT NULL AND length(excluded.media_key)>0 THEN excluded.media_key ELSE messages.media_key END,
    file_sha256=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN CASE WHEN messages.file_sha256 IS NOT NULL AND length(messages.file_sha256)>0 THEN messages.file_sha256 ELSE excluded.file_sha256 END WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.file_sha256 WHEN excluded.file_sha256 IS NOT NULL AND length(excluded.file_sha256)>0 THEN excluded.file_sha256 ELSE messages.file_sha256 END,
    file_enc_sha256=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN CASE WHEN messages.file_enc_sha256 IS NOT NULL AND length(messages.file_enc_sha256)>0 THEN messages.file_enc_sha256 ELSE excluded.file_enc_sha256 END WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.file_enc_sha256 WHEN excluded.file_enc_sha256 IS NOT NULL AND length(excluded.file_enc_sha256)>0 THEN excluded.file_enc_sha256 ELSE messages.file_enc_sha256 END,
    file_length=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN CASE WHEN messages.file_length IS NOT NULL AND messages.file_length>0 THEN messages.file_length ELSE excluded.file_length END WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.file_length WHEN excluded.file_length>0 THEN excluded.file_length ELSE messages.file_length END,
    local_path=messages.local_path,
    downloaded_at=messages.downloaded_at,
    media_unavailable_at=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN messages.media_unavailable_at WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.media_unavailable_at WHEN COALESCE(excluded.direct_path,'') != '' AND excluded.direct_path != COALESCE(messages.direct_path,'') THEN NULL ELSE messages.media_unavailable_at END,
    revoked=CASE WHEN excluded.revoked != 0 THEN 1 ELSE messages.revoked END,
    deleted_for_me=CASE WHEN excluded.deleted_for_me != 0 THEN 1 ELSE messages.deleted_for_me END,
    deleted_at=COALESCE(messages.deleted_at, excluded.deleted_at),
    deletion_reason=CASE WHEN messages.deleted_at IS NOT NULL THEN COALESCE(NULLIF(messages.deletion_reason,''), excluded.deletion_reason) ELSE excluded.deletion_reason END,
    edited=CASE WHEN messages.deleted_at IS NOT NULL THEN messages.edited WHEN excluded.deleted_at IS NOT NULL THEN 0 WHEN excluded.edited != 0 THEN 1 WHEN messages.edited != 0 THEN messages.edited ELSE 0 END,
    edited_ts=CASE WHEN messages.deleted_at IS NOT NULL THEN messages.edited_ts WHEN excluded.deleted_at IS NOT NULL THEN 0 WHEN excluded.edited != 0 AND (messages.edited = 0 OR excluded.edited_ts > messages.edited_ts) THEN excluded.edited_ts WHEN messages.edited != 0 THEN messages.edited_ts ELSE 0 END,
    buttons=CASE WHEN messages.deleted_at IS NOT NULL OR excluded.deleted_at IS NOT NULL THEN COALESCE(messages.buttons, excluded.buttons) WHEN (messages.edited != 0 AND excluded.edited = 0) OR (messages.edited != 0 AND excluded.edited != 0 AND excluded.edited_ts < messages.edited_ts) OR (messages.edited = 0 AND excluded.edited = 0 AND excluded.ts < messages.ts) THEN messages.buttons ELSE excluded.buttons END
WHERE messages.payload_purged_at IS NULL
`

type UpsertMessageParams struct {
	ChatJid         string
	ChatName        sql.NullString
	MsgID           string
	SenderJid       sql.NullString
	SenderName      sql.NullString
	Ts              int64
	FromMe          int64
	Text            sql.NullString
	DisplayText     sql.NullString
	QuotedMsgID     sql.NullString
	QuotedSenderJid sql.NullString
	IsForwarded     int64
	ForwardingScore int64
	ReactionToID    sql.NullString
	ReactionEmoji   sql.NullString
	MediaType       sql.NullString
	MediaCaption    sql.NullString
	Filename        sql.NullString
	MimeType        sql.NullString
	DirectPath      sql.NullString
	MediaKey        []byte
	FileSha256      []byte
	FileEncSha256   []byte
	FileLength      sql.NullInt64
	Revoked         int64
	DeletedForMe    int64
	DeletedAt       sql.NullInt64
	DeletionReason  sql.NullString
	Edited          int64
	EditedTs        int64
	Buttons         sql.NullString
	ChatJid_2       string
	MsgID_2         string
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.ChatJid,
		arg.ChatName,
		arg.MsgID,
		arg.SenderJid,
		arg.SenderName,
		arg.Ts,
		arg.FromMe,
		arg.Text,
		arg.DisplayText,
		arg.QuotedMsgID,
		arg.QuotedSenderJid,
		arg.IsForwarded,
		arg.ForwardingScore,
		arg.ReactionToID,
		arg.ReactionEmoji,
		arg.MediaType,
		arg.MediaCaption,
		arg.Filename,
		arg.MimeType,
		arg.DirectPath,
		arg.MediaKey,
		arg.FileSha256,
		arg.FileEncSha256,
		arg.FileLength,
		arg.Revoked,
		arg.DeletedForMe,
		arg.DeletedAt,
		arg.DeletionReason,
		arg.Edited,
		arg.EditedTs,
		arg.Buttons,
		arg.ChatJid_2,
		arg.MsgID_2,
	)
	return err
}

const upsertMessageLocation = `-- name: UpsertMessageLocation :exec
INSERT INTO message_locations (chat_jid, msg_id, latitude, longitude, name, address, is_live)
SELECT ?, ?, ?, ?, ?, ?, ?
WHERE NOT EXISTS (
    SELECT 1 FROM message_payload_purges p WHERE p.chat_jid = ? AND p.msg_id = ?
)
ON CONFLICT(chat_jid, msg_id) DO UPDATE SET
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    name = excluded.name,
    address = excluded.address,
    is_live = excluded.is_live
`

type UpsertMessageLocationParams struct {
	ChatJid   string
	MsgID     string
	Latitude  float64
	Longitude float64
	Name      sql.NullString
	Address   sql.NullString
	IsLive    int64
	ChatJid_2 string
	MsgID_2   string
}

func (q *Queries) UpsertMessageLocation(ctx context.Context, arg UpsertMessageLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessageLocation,
		arg.ChatJid,
		arg.MsgID,
		arg.Latitude,
		arg.Longitude,
		arg.Name,
		arg.Address,
		arg.IsLive,
		arg.ChatJid_2,
		arg.MsgID_2,
	)
	return err
}

const upsertPoll = `-- name: UpsertPoll :exec
INSERT INTO polls (chat_jid, msg_id, sender_jid, question, options_json, selectable_count, created_ts)
SELECT ?, ?, ?, ?, ?, ?, ?
WHERE NOT EXISTS (
    SELECT 1 FROM message_payload_purges p WHERE p.chat_jid = ? AND p.msg_id = ?
)
ON CONFLICT(chat_jid, msg_id) DO UPDATE SET
    sender_jid = excluded.sender_jid,
    question = excluded.question,
    options_json = excluded.options_json,
    selectable_count = excluded.selectable_count,
    created_ts = excluded.created_ts
`

type UpsertPollParams struct {
	ChatJid         string
	MsgID           string
	SenderJid       sql.NullString
	Question        string
	OptionsJson     string
	SelectableCount int64
	CreatedTs       int64
	ChatJid_2       string
	MsgID_2         string
}

func (q *Queries) UpsertPoll(ctx context.Context, arg UpsertPollParams) error {
	_, err := q.db.ExecContext(ctx, upsertPoll,
		arg.ChatJid,
		arg.MsgID,
		arg.SenderJid,
		arg.Question,
		arg.OptionsJson,
		arg.SelectableCount,
		arg.CreatedTs,
		arg.ChatJid_2,
		arg.MsgID_2,
	)
	return err
}

const upsertPollVote = `-- name: UpsertPollVote :exec
INSERT INTO poll_votes (chat_jid, poll_msg_id, voter_jid, vote_msg_id, selected_options_json, ts)
SELECT ?, ?, ?, ?, ?, ?
WHERE NOT EXISTS (
    SELECT 1 FROM message_payload_purges p WHERE p.chat_jid = ? AND p.msg_id = ?
)
  AND NOT EXISTS (
    SELECT 1 FROM message_payload_purges p WHERE p.chat_jid = ? AND p.msg_id = ?
)
ON CONFLICT(chat_jid, poll_msg_id, voter_jid) DO UPDATE SET
    vote_msg_id = excluded.vote_msg_id,
    selected_options_json = excluded.selected_options_json,
    ts = excluded.ts
WHERE excluded.ts >= poll_votes.ts
`

type UpsertPollVoteParams struct {
	ChatJid             string
	PollMsgID           string
	VoterJid            string
	VoteMsgID           string
	SelectedOptionsJson string
	Ts                  int64
	ChatJid_2           string
	MsgID               string
	ChatJid_3           string
	MsgID_2             string
}

func (q *Queries) UpsertPollVote(ctx context.Context, arg UpsertPollVoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertPollVote,
		arg.ChatJid,
		arg.PollMsgID,
		arg.VoterJid,
		arg.VoteMsgID,
		arg.SelectedOptionsJson,
		arg.Ts,
		arg.ChatJid_2,
		arg.MsgID,
		arg.ChatJid_3,
		arg.MsgID_2,
	)
	return err
}
